"""empty message

Revision ID: 75622a8b9ddf
Revises: 3707fbe3b686
Create Date: 2019-10-13 15:29:17.958391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75622a8b9ddf'
down_revision = '3707fbe3b686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('commenter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['commenter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'commenter_id')
    # ### end Alembic commands ###
